name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: devops_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install flask psycopg2-binary pytest requests

      - name: Wait for Database to Be Ready
        run: |
          for i in {1..10}; do
            nc -z localhost 5432 && echo "Database is ready" && exit 0
            echo "Waiting for database..."
            sleep 3
          done
          echo "Database did not become ready in time" && exit 1

      - name: Start Flask App in Background
        run: |
          python app.py &
          sleep 5  # Wait for the app to start

      - name: Run Tests
        run: pytest tests/

  build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t yourdockerhubusername/devops-flask-app .
          docker tag yourdockerhubusername/devops-flask-app:latest
          docker push yourdockerhubusername/devops-flask-app:latest
